Build ITLab via python script
RTUITLab/ITLab pull request #15
Opened 2022-02-03 20:10 UTC by Suput

2022-02-03 20:57 UTC, CAPCHIK requested changes
Python файлы не смотрел, тут полагаюсь на @TheDim0n 
@Suput все начатые ветки или ответь там как-то или закрой, если ответа не надо

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +      1. Double-click from Explorer folder on "./ITLab/Proxy/certs/localhost.crt" file
Ты изъясняешься уже из ITLab,  стоит писать сразу `Proxy/ ...`, и в начале `./` не нужны

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +      4. Click "Next.", select "Place all certificates in the following store."
Не уверен, что в этом и трем пунктах далее и правда есть точка в UI винды

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +      1. Search methods in the Internet
Может стоит хоть какую-то ссылку приложить?)

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +3. Build ITLab's Front part
Стоит дописать, что тут собирается фронт через Node.JS, и да, она получается нужна в Requirements

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
>  > Default user: email="`admin`" password="`Pa$$word1243`"
Кажется это дублирование, можно просто сказать "идите выше"

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +- `--docker` flag allows you to run any docker script using all found `docker-compose.yml` files. How to use: place your docker-compose command after equals (`=`) symbol in quotes (`"`). It's necessa
`any docker script` возможно стоит заменить на `any docker-compose command` или даже без тире

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +- `--docker` flag allows you to run any docker script using all found `docker-compose.yml` files. How to use: place your docker-compose command after equals (`=`) symbol in quotes (`"`). It's necessa
quotes это `'`, я бы явно написал double

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +- `--no-cache` flag determines not to use cachefiles for `docker-compose.yml` files. Explanation: without cache or `--no-cache` flag `build.py` script searches every folder (even in subfolders) for `
Я так понимаю складываешь список файлов куда-то на время? В плане он долго ищет файлы?

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +Requirements
А вот тут нода уже и не нужна, просто напоминаю

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +   # dbs
Ну это же комментарий, можно уж и не скупиться, что за dbs?

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +   MARIA_SERVER_ROOT_USERNAME=username
Напомни, где у нас вообще еще используется Mysql? Если в покупках - то не забудь поправить потом

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +   ITLAB_EMAIL_SENDER_BASE_ADDRESS=https://www.my.email.sender.domain.com
Возможно стоит приложить где-то линк на репозиторий с отправляльщиком, что мы говорим про воот этот сервис

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +   ITLAB_EMAIL_TEMPLATE_INVITATION_URL=https://www.my.email.invite.template.com/1.html
Вот возможно тут надо бы сослаться на страницу с документацией, какие поля для подстановки доступны для этого шаблона, как его составить, и что во фвронте можно найти примеры

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
> +   ITLAB_NOTIFY_DB_PORT=8080
**Надо** поменять это все и везде на строку подключения, по опыту эта разбивка по параметрам в один прекрасный день не дает что-то дополнительное сконфигурировать, это вброс на будущее, что везде параметры для подключения к внешнему сервису надо указывать строкой подключения, а не отдельно полями. Парсеры есть везде

2022-02-03 20:57 UTC, CAPCHIK commented on README.md
>  ## Architecture
Кажется архитектура не правилась, будет отдельным PR?

2022-02-03 20:57 UTC, CAPCHIK commented on build.py
> +        docker_config(
Возможно стоит переименовать в `create_stack` или подобное?

2022-02-03 20:57 UTC, CAPCHIK commented on build/__init__.py
> +# This file needs for python to thinks that this folder is a package
Возможно @TheDim0n знает, что сюда можно прописать чуть более полезного, чем просто комментарий

2022-02-04 09:20 UTC, Suput commented on README.md
>  > Default user: email="`admin`" password="`Pa$$word1243`"
Дублирование чего?

2022-02-04 09:24 UTC, Suput commented on README.md
> +- `--no-cache` flag determines not to use cachefiles for `docker-compose.yml` files. Explanation: without cache or `--no-cache` flag `build.py` script searches every folder (even in subfolders) for `
Вот как это происходит: он ищет во всех папках файлы каждый раз  
Я подумал - "зачем искать каждый раз, если новые файлы добавляются редко"  
Так родилась идея сделать cachefile, в котором будут хранится пути до файлов

То есть мой скрипт будет искать сначала cachefile, если он есть - считать его контент (это пути до файлов) и использовать его. Если кэша нет - найти все файлы, использовать найденные пути, и заодно сложить в кэш, чтобы в дальнейшем было быстрее

2022-02-04 09:27 UTC, Suput commented on README.md
> +   MARIA_SERVER_ROOT_USERNAME=username
В покупках и пассболте. Что поправлять?
Это общее название сервера и пароля, они не имеют отношения к сервису
В сервисе может быть следующая строка
`EXAMPLE="User ID=user;Password=$Env:PASSWORD;Server=$Env:SERVER_NAME;Port=80;Database=database`

2022-02-04 09:29 UTC, Suput commented on README.md
> +   ITLAB_EMAIL_TEMPLATE_INVITATION_URL=https://www.my.email.invite.template.com/1.html
То есть где-то описать, как составить свой шаблон для приглашений и восстановления пароля?

2022-02-04 09:29 UTC, Suput commented on README.md
> +   ITLAB_NOTIFY_DB_PORT=8080
Я тебя прекрасно понимаю. Но первая версия написана именно так. Поэтому пришлось делать так..
Я тоже ЗА одну строку

2022-02-04 09:30 UTC, CAPCHIK commented on README.md
>  > Default user: email="`admin`" password="`Pa$$word1243`"
логин парполь

2022-02-04 09:30 UTC, CAPCHIK commented on README.md
> +   ITLAB_EMAIL_TEMPLATE_INVITATION_URL=https://www.my.email.invite.template.com/1.html
Ну да, в идеале, или просто дать ссылку на готовые шаблоны

2022-02-04 09:30 UTC, Suput commented on README.md
>  ## Architecture
Я когда-то просто удалил картинку старой архитектуры и оставил только новую. Потому что старая совсем не актуальной было

2022-02-04 09:31 UTC, CAPCHIK commented on README.md
>  ## Architecture
Так и новая кажется изменилась, нет?

2022-02-04 09:32 UTC, Suput commented on build/__init__.py
> +# This file needs for python to thinks that this folder is a package
Да. Если @TheDim0n знает - скажи пожалуйста
По опыту - PyCharm работает по своему, Visual Studio Code по своему, из консоли вообще по другому
VS Code не видел папку с другими скриптами, нашёл в инете, что этой папке нужен `__init__.py` скрипт. Я засунул туда комментарий, чтобы не оставлять его пустым

2022-02-04 09:53 UTC, CAPCHIK commented on README.md
> +- `--no-cache` flag determines not to use cachefiles for `docker-compose.yml` files. Explanation: without cache or `--no-cache` flag `build.py` script searches every folder (even in subfolders) for `
Окей, если по скорости есть эффект - круто, что такая фича есть 👍

2022-02-04 09:55 UTC, CAPCHIK commented on README.md
> +   MARIA_SERVER_ROOT_USERNAME=username
Поправить - в покупках уже используется постгрес, но кажется он еще не опубликован

А пассболт не относится к ITLab, так что MARIA надо будет в итоге удалить, просто пишу, чтобы точно не забылось

2022-02-04 09:56 UTC, CAPCHIK approved these changes
Уже лучше, надо чтобы все обсуждения выше были закрыты

2022-02-04 09:57 UTC, Suput commented on README.md
>  ## Architecture
Изменилась, но я не переделывал картинку(

2022-02-04 09:58 UTC, Suput commented on README.md
>  > Default user: email="`admin`" password="`Pa$$word1243`"
Пусть будет?
Заходит человек прожённый - зачем ему листать вниз, до этого пункта, чтобы увидеть логин пароль  
Заходит человек не прожённый - выполнил все шаги, уже забыл, что наверху ему сказали про логин и пароль, увидел его сейчас, использовал

2022-02-04 10:02 UTC, CAPCHIK commented on README.md
>  > Default user: email="`admin`" password="`Pa$$word1243`"
Ок, в общем-то эти параметры будут меняться раз в 100 лет, так что согласен

2022-02-04 10:02 UTC, CAPCHIK commented on README.md
>  ## Architecture
Ок, значит будет вместе с нормальной докой и  прочим, позже 👌

2022-02-04 20:09 UTC, TheDim0n commented on build/__init__.py
> +# This file needs for python to thinks that this folder is a package
__init__.py зачастую пустой и это нормально - он нужен, чтобы Python мог распознать папку как локальный пакет, из которого можно что-то импортировать
Так что тут все нормально

2022-02-04 21:38 UTC, TheDim0n commented on build/CONSTS.py
> +    os.path.join(os.getcwd(), "ITLab-Back-Root",
Кажется надежнее `os.path.dirname(__file__)`

2022-02-04 21:39 UTC, TheDim0n commented on build/CONSTS.py
> +FRONT_ROOT_FOLDER_FULL_PATH = os.path.join(os.getcwd(), FRONT_ROOT_FOLDER_NAME)
Так же `os.path.dirname(__file__)`

2022-02-04 22:04 UTC, TheDim0n commented on build/CONSTS.py
> +
Вроде не принято именовать файлы `.py` uppercase'ом (по крайне мере никогда такого не видел)

2022-02-04 22:07 UTC, TheDim0n reviewed
Подправить codestyle под PEP8 (точно импорты, где-то видел одну пустую строчку вместо двух, может быть в паре мест длина строки > 79). Для этого советую настроить `flake8` в VSCode (можно у меня попросить json с параметрами для IDE).

Не понятно зачем перезаписывать `.env*` в `os.environ` и считывать их снова из `os.environ` - уже ведь считали из `.env*`. Плюс можно сказать `docker-compose` какой именно `.env*` считывать

2022-02-07 10:20 UTC, Suput commented
> Плюс можно сказать docker-compose какой именно .env* считывать

`-c {dev, prod}` решает этот вопрос - файлы, что для прода, что для дева одни и те же. Это `docker-compose.yml` и `docker-compose.prod.yml`. А флаг `-c` решает вопрос какой `env` использовать - для дева или для прода  
Пояснение зачем это нужно: я сделал два отдельных `env` с целью, чтобы человек мог иметь два окружения под рукой и не перезаписывать каждый раз файл из 50 строк и хранить переменные для разных окружений в каких-то файлах

> Не понятно зачем перезаписывать .env* в os.environ и считывать их снова из os.environ - уже ведь считали из .env*.

~~Потому что записываю я одни переменные, а считываю другие переменные~~
Потому что в ITLab есть общие переменные, которые ни от кого не зависят. Эти все переменные вынесены в общий файл, который не зависит от ОС. Переменные я считываю и записываю их в переменные окружения.  
Во-первых, они нужны для каких-то сервисов.  
Во-вторых, от этих переменных зависят другие переменные. Поэтому я сначала записываю их в переменные окружения, а потом от туда достаю.  
Ты предлагаешь сначала всё считать в какую переменную (допусти словарь), а потом весь словарь экспортировать в переменные окружения? В целом это может выглядеть красивей, согласен. Сделаю так

> PEP8

У меня стоит какой-то PEP8, который не ругается ни на что. Код для меня читабельный. Если ты мне скинешь в том же Slack инструкцию по настройке нового PEP8 я буду рад

@TheDim0n

2022-02-07 12:00 UTC, CAPCHIK approved these changes

2022-02-07 12:00 UTC, CAPCHIK commented on README.md
> +   # databases configuration
Yay!

2022-02-07 12:00 UTC, CAPCHIK commented on README.md
> +   # how to generate templates - watch https://github.com/RTUITLab/ITLab-Front
Yay!

2022-02-07 12:00 UTC, CAPCHIK commented on README.md
> +   # ITLAB_EMAIL_TEMPLATE_RESET_PASSWORD_URL=https://raw.githubusercontent.com/RTUITLab/ITLab-Front/master/mail_templates/password_restore.html
Отлично

2022-02-08 17:50 UTC, TheDim0n approved these changes

2022-02-08 21:43 UTC, merged